version: '3.7'

services:

  rtc:
    image: 'openvidu/openvidu-server-kms:2.22.0'
    environment:
      - "OPENVIDU_SECRET=MY_SECRET_KEY_123"
      - "OPENVIDU_RECORDING=true"
      - "OPENVIDU_RECORDING_PATH=/recordings"
      - "DOMAIN_OR_PUBLIC_IP=192.168.0.84"

    ports:
      - "4443:4443"

    volumes:
      - .:/crosstalk
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data/recordings:/recordings

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - "OPENVIDU_URL=https://192.168.0.84:4443/"
      - "OPENVIDU_SECRET=MY_SECRET_KEY_123"
      - "GAME_LOG=/game_logs"
      - "GAME_DATA=/game_data"
      - "NODE_TLS_REJECT_UNAUTHORIZED=0"  # avoid OV.createSession rejection
    volumes:
      - .:/app
      - ./.data/game_logs:/game_logs
      - ./.data/game_data:/game_data
    depends_on:
      - rtc

  data-server:
    build:
      context: .
      dockerfile: Dockerfile-data-server
    ports:
      - "8000:8000"
    environment:
      - "GAME_DATA=/game_data"
      - "VIDEO_DATA=/video_data"
      - "ACCESS_PASSWORD=pw"
    volumes:
      - .:/app
      - ./.data/game_data:/game_data
      - ./.data/recordings:/video_data
